Q1) Write a Python function that takes a list and returns a new list with distinct elements from
the first list.

In [1]:
# defining the function
def new_list(input_list):
  return list(set(input_list))

# usage
input_list=[1,1,2,2,2,3,4,55,55,6,6]
print(new_list(input_list))

[1, 2, 3, 4, 6, 55]

Q2) Write a Python program to access a function inside a function.

In [2]:
def outer_fn():
  def inner_fn():
    print('This is inner function')

  print('This is outer function')
  inner_fn()

outer_fn()

This is outer function
This is inner function

Q3) Use a loop to display elements from a given list present at odd index positions.

In [3]:
l1 = [10,20,30,40,50,60,70,80,90]
for i in range(1, len(l1), 2):
  print(l1[i])

20
40
60
80

Q4)  Write a program to print the following star pattern using the for loop

In [4]:
n=5
for i in range(n):
  for j in range(i+1):
    print("* ", end="")
  print()

for i in range(n-1,0,-1):
  for j in range(i):
    print("* ", end="")
  print()

*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*

Q5) Write a program to accept a number from a user and calculate the sum of all numbers
from 1 to a given number

In [5]:
def add_num(n):
  sum_of_nums=0
  for i in range(1,n+1):
    sum_of_nums += i
  return sum_of_nums

n = int(input("enter the number : "))
sum = add_num(n)

print(f"sum of all numbers from 1 to {n} is" , sum)

enter the number : 10
sum of all numbers from 1 to 10 is 55

Q5) Write a program to increase those values in the given Pandas Series by 50 which are
less than 70.

In [6]:
import pandas as
l2=[10,20,30,40,50,100,150,250]
s2=pd.Series(l2)
s2=s2.apply(lambda x: x+50 if x<70 else x)
s2

NameError: name 'pd' is not defined