In [1]:
# importing libraries
import pandas as pd
import numpy as np

**Q1) create  series object which stores the total number candidates in the 5 sections of an MNC company(name them)**

In [2]:
sec = {'tech':1000,
       'hr':500,
       'support':2000,
       'leads':200,
       'associate':1500}
mnc=pd.Series(sec)
mnc

tech         1000
hr            500
support      2000
leads         200
associate    1500
dtype: int64

**Q2) write code to modify the 2nd,4th,5th section**

In [3]:
mnc["tech"]=750
mnc

tech          750
hr            500
support      2000
leads         200
associate    1500
dtype: int64

**Q3) consiedr two series object A! and A2 which stores total students in science,commerece and humaniies write code to finf total num of the students of both series object streawise**

In [4]:
class_11={'science':100,
          'commerce':150,
          'humanity':250}
class_12={'science':105,
          'commerce':155,
          'humanity':255}

In [5]:
clas_11=pd.Series(class_11)
clas_12=pd.Series(class_12)

In [6]:
total_stud=clas_11+clas_12
total_stud

science     205
commerce    305
humanity    505
dtype: int64

**Q4) create a series object of population storing details of four different metro cities of india ad object 2 consists total average icome of population and in those cities calculate per capita income for each city**

In [7]:
cit={'mumbai':150000,
     'delhi':250000,
     "kol":100000,
     "chen":300000}
avg_inc={'mumbai':1500,
     'delhi':2500,
     "kol":1000,
     "chen":3000}

In [8]:
city=pd.Series(cit)
inc=pd.Series(avg_inc)
per_cap_inc=city/inc
per_cap_inc

mumbai    100.0
delhi     100.0
kol       100.0
chen      100.0
dtype: float64